-- AddQuickGameTopicTypes
-- 快問新增題型：簡答題 / 連連看 / 拼圖題 / 刮刮樂 / 轉盤抽獎 / 日式搖獎

ALTER TYPE "TopicType" ADD VALUE IF NOT EXISTS 'SHORT_ANSWER';
ALTER TYPE "TopicType" ADD VALUE IF NOT EXISTS 'MATCHING';
ALTER TYPE "TopicType" ADD VALUE IF NOT EXISTS 'PUZZLE';
ALTER TYPE "TopicType" ADD VALUE IF NOT EXISTS 'SCRATCH';
ALTER TYPE "TopicType" ADD VALUE IF NOT EXISTS 'SPIN_WHEEL';
ALTER TYPE "TopicType" ADD VALUE IF NOT EXISTS 'LOTTERY';

ALTER TABLE "topic_options" ADD COLUMN IF NOT EXISTS "data" JSONB;

ALTER TABLE "votes" ADD COLUMN IF NOT EXISTS "answer_text" TEXT;