name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - name: Prisma generate
        run: npm run prisma:generate
        working-directory: apps/api
      - name: Build API
        run: npm run build -w apps/api
      - name: Test API
        run: npm run test -w apps/api
      - name: Build Web
        run: npm run build -w apps/web
